blueprint:
  name: "Wake-up light alarm with realistic sunrise effect. Version: 1.6.0"
  description: >
    A wake-up light alarm with a realistic brightness and color temperature sunrise effect.
    Supports either manual time/weekday scheduling or scheduler helper.
  domain: automation
  homeassistant:
    min_version: "2023.1.0"
  input:
    schedule_type:
      name: Schedule Type
      description: Choose whether to use manual scheduling or a scheduler helper
      default: manual
      selector:
        select:
          options:
            - label: Manual (Time + Weekdays)
              value: manual
            - label: Scheduler Helper
              value: scheduler
            - label: None (Event Only)
              value: none
          required: true
    alarm_time:
      name: Alarm Time
      description: The time to trigger the sunrise alarm
      selector:
        time:
          required: "{{ schedule_type == 'manual' }}"
          show_if: "{{ schedule_type == 'manual' }}"
    weekdays:
      name: Active Days
      description: Days when the alarm should be active (comma-separated, e.g., 'mon,tue,wed')
      default: "mon,tue,wed,thu,fri"
      selector:
        text:
          required: "{{ schedule_type == 'manual' }}"
          show_if: "{{ schedule_type == 'manual' }}"
    scheduler_helper:
      name: Scheduler Helper
      description: Select a scheduler helper entity
      selector:
        entity:
          domain: schedule
          required: "{{ schedule_type == 'scheduler' }}"
          show_if: "{{ schedule_type == 'scheduler' }}"
    light_entity:
      name: Wake-up light entity
      description: The light to control. Color temperature range is auto-detected.
      selector:
        entity:
          domain: light
      required: true
    sunrise_duration:
      name: Sunrise duration
      description: The sunrise will start this many minutes before the timestamp.
      default: 30
      selector:
        number:
          min: 10
          max: 60
          step: 5
          unit_of_measurement: min
          mode: slider
    end_brightness:
      name: Ending brightness
      description: The final brightness level of the light at the end of the sunrise effect.
      default: 100
      selector:
        number:
          min: 10
          max: 100
          step: 1
          mode: slider
          unit_of_measurement: "%"
    keep_on_duration:
      name: Keep light on duration
      description: How long to keep the light on after the sunrise effect is complete.
      default: 60
      selector:
        number:
          min: 5
          max: 120
          step: 5
          unit_of_measurement: min
          mode: slider

variables:
  light_entity: !input light_entity
  sunrise_duration: !input sunrise_duration
  start_brightness: 1
  end_brightness: !input end_brightness
  update_interval: 10 # Update every 10 seconds
  total_updates: "{{ ((sunrise_duration | int) * 60 / update_interval) | int }}"
  color_steps: [
      [139, 0, 0], # Deep dark red
      [205, 16, 0], # Dark red
      [255, 69, 0], # Red-orange
      [255, 130, 0], # Deep orange
      [255, 180, 50], # Golden yellow
      [255, 223, 150], # Very warm white/golden
    ]
  keep_on_duration: !input keep_on_duration
  # Process and validate manual schedule inputs
  days: "{{ (weekdays | default('')) | lower | regex_replace(' ', '') | regex_replace('[^a-z,]', '') | split(',') }}"
  has_valid_manual_schedule: "{{ schedule_type == 'manual'
                                and alarm_time is not none
                                and days|length > 0 }}"
  # Process and validate scheduler input
  has_valid_scheduler: "{{ schedule_type == 'scheduler'
                          and scheduler_helper is not none }}"
  scheduler_entity: "{{ scheduler_helper if schedule_type == 'scheduler' else none }}"
  alarm_time_input: "{{ alarm_time if schedule_type == 'manual' else none }}"

trigger:
  # Manual schedule trigger
  - platform: time
    at: !input alarm_time
    enabled: "{{ has_valid_manual_schedule }}"
    variables:
      current_day: "{{ now().strftime('%a') | lower }}"
    condition:
      - condition: template
        value_template: "{{ current_day in days }}"

  # Scheduler helper trigger
  - platform: state
    enabled: "{{ has_valid_scheduler }}"
    entity_id: !input scheduler_helper
    to: "on"

action:
  # Set initial state
  - action: light.turn_on
    target:
      entity_id: !input light_entity
    data:
      brightness: "{{ start_brightness * 2.55 | round(0) }}"
      rgb_color: "{{ color_steps[0] }}"
      transition: "{{ update_interval }}"
  - delay:
      seconds: "{{ update_interval }}"

  - repeat:
      count: "{{ total_updates }}"
      sequence:
        - condition: state
          entity_id: !input light_entity
          state: "on"
        - variables:
            progress: "{{ repeat.index / total_updates }}"
            current_brightness: >
              {{ ((progress ** 2) * (end_brightness - start_brightness) + start_brightness) * 2.55 | round(0) }}
            color_progress: "{{ progress * (color_steps | length - 1) }}"
            color_index: "{{ color_progress | int }}"
        - action: light.turn_on
          target:
            entity_id: !input light_entity
          data:
            brightness: "{{ current_brightness }}"
            rgb_color: >
              {% set start = color_steps[color_index] %}
              {% set end = color_steps[color_index + 1] %}
              {% set fraction = color_progress - color_index %}
              {{ [
                (start[0] + (end[0] - start[0]) * fraction) | round,
                (start[1] + (end[1] - start[1]) * fraction) | round,
                (start[2] + (end[2] - start[2]) * fraction) | round
              ] }}
            transition: "{{ update_interval }}"
        - delay:
            seconds: "{{ update_interval }}"
        - if:
            - condition: or
              conditions:
                - condition: state
                  entity_id: !input light_entity
                  state: "off"
                - condition: template
                  value_template: "{{ repeat.index == total_updates - 1 }}"
          then:
            - choose:
                - conditions:
                    - condition: state
                      entity_id: !input light_entity
                      state: "off"
                  sequence:
                    - stop: "Light turned off, aborting sunrise"
                - conditions:
                    - condition: template
                      value_template: "{{ repeat.index == total_updates - 1 }}"
                  sequence:
                    - if:
                        condition: template
                        value_template: "{{ keep_on_duration > 0 }}"
                      then:
                        - delay:
                            minutes: "{{ keep_on_duration }}"
                        - action: light.turn_off
                          target:
                            entity_id: !input light_entity
                          data:
                            transition: 30
                    - stop: "Sunrise complete"

mode: single
max_exceeded: silent
