blueprint:
  name: ZHA Philips Hue Dimmer Switch (RWL022) (Scene Preset)
  description: Control lights with a Philips Hue Dimmer Switch. Scene Preset integration is required https://github.com/Hypfer/hass-scene_presets
  domain: automation
  input:
    dimmer_switch:
      name: Dimmer Switch
      description: The dimmer switch to use
      selector:
        device:
          integration: zha
          model: RWL022
          multiple: false
    light:
      name: Lights
      description: The lights to control with + / - and to turn off
      selector:
        entity:
          domain:
            - light
          multiple: false
    included_scenes:
      name: Hue Button Scenes
      description: Scenes to be included. The first scene will be used only for the main ON button.
      default: []
      selector:
        select:
          mode: dropdown
          options:
            - label: Rest
              value: e03267e7-9914-4f47-97fe-63c0bd317fe7
            - label: Relax
              value: e71b2ef3-1b15-4c4b-b036-4b3d6efe58f8
            - label: Read
              value: 035b6ecf-414e-4781-abc7-3911556097cb
            - label: Concentrate
              value: 0cbec4e8-d064-4457-986a-fe6078a63f39
            - label: Bright
              value: 6d10a807-7330-46d1-b093-c15520ba72c0
            - label: Dimmed
              value: 8f55e62a-e5f8-456a-9e8b-61f314bd4e99
            - label: Galaxy
              value: a6ba3a6e-1e3a-41fd-84f2-f7b021935deb
          multiple: true
    scene_helper:
      name: Scene Helper
      description: Please select an Input Text Helper to be used to record the scene sequence in JSON format with timestamp.
      selector:
        entity:
          domain:
            - input_text
          multiple: false
    transition_time:
      name: Transition Time
      description: Transition time when changes
      default: 1
      selector:
        number:
          min: 0.0
          max: 3.0
          step: 0.1
          unit_of_measurement: sec
          mode: slider
    hold_press_change:
      name: Hold Press Change
      description: Transition time between changes
      default: 17
      selector:
        number:
          min: 0.0
          max: 25.0
          step: 1.0
          unit_of_measurement: "%"
          mode: slider
    reset_after:
      name: Reset After
      description: Timeout in seconds after which the order is reset to the first scene.
      default: 5
      selector:
        number:
          min: 1.0
          max: 120.0
          step: 1.0
          unit_of_measurement: s
          mode: slider
mode: queued
max_exceeded: silent
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input dimmer_switch
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      included_scenes: !input included_scenes
      scene_helper: !input scene_helper
      reset_after: !input reset_after
      target_lights: !input light
      hold_press_change: !input hold_press_change
      current_scene: >
        {% set data = states(scene_helper) %}
        {% if data != "unknown" %}
          {% if (as_timestamp(now()) - (data | from_json).timestamp) < reset_after %}
            {{ (data | from_json).scene }}
          {% else %}
          1
          {% endif %}
        {% else %}
          1
        {% endif %}
  - choose:
      - conditions:
          - "{{ command == 'on_press' }}"
        sequence:
          - choose:
              - conditions: "{{ states(target_lights) == 'off' }}"
                sequence:
                  - service: scene_presets.apply_preset
                    data:
                      preset_id: "{{ included_scenes[0] }}"
                      targets:
                        entity_id: !input light
                      shuffle: false
                      smart_shuffle: false
              - conditions: "{{ states(target_lights) == 'on' }}"
                sequence:
                  - service: light.turn_off
                    target:
                      entity_id: !input light
                    data:
                      transition: !input transition_time
      - conditions:
          - "{{ command == 'on_double_press' }}"
        sequence:
          - service: scene_presets.apply_preset
            data:
              preset_id: "{{ included_scenes[0] }}"
              targets:
                entity_id: !input light
              shuffle: false
              smart_shuffle: false
      - conditions:
          - "{{ command == 'up_hold' or command == 'up_press'}}"
        sequence:
          - choose:
              - conditions:
                  "{{ (state_attr(target_lights, 'brightness') + ((hold_press_change/100)*254)
                  | round)  <= 255 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                        | map(attribute='entity_id') | list }}"
                    data:
                      brightness_step_pct: "{{ hold_press_change }}"
                      transition: !input transition_time
              - conditions:
                  "{{ (state_attr(target_lights, 'brightness') + ((hold_press_change/100)*254)
                  | round)  > 255 }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                        | map(attribute='entity_id') | list }}"
                    data:
                      brightness_pct: 100
                      transition: !input transition_time
      - conditions: "{{ command == 'up_double_press' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                | map(attribute='entity_id') | list }}"
            data:
              brightness_pct: 100
              transition: !input transition_time
      - conditions:
          - "{{ command == 'down_hold' or command == 'down_press' }}"
        sequence:
          - choose:
              - conditions:
                  "{{ (state_attr(target_lights, 'brightness') - ((hold_press_change/100)*254)
                  | round)  >= hold_press_change }}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                        | map(attribute='entity_id') | list }}"
                    data:
                      brightness_step_pct: "{{ -hold_press_change }}"
                      transition: !input transition_time
              - conditions:
                  "{{ (state_attr(target_lights, 'brightness') - ((hold_press_change/100)*254)
                  | round)  < hold_press_change or (state_attr(target_lights, 'brightness')
                  - ((hold_press_change/100)*254) | round)  >= 1}}"
                sequence:
                  - service: light.turn_on
                    target:
                      entity_id:
                        "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                        | map(attribute='entity_id') | list }}"
                    data:
                      brightness_pct: 1
                      transition: !input transition_time
      - conditions: "{{ command == 'down_double_press' }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id:
                "{{ expand(target_lights) | selectattr('state', 'eq', 'on')
                | map(attribute='entity_id') | list }}"
            data:
              brightness_pct: 1
              transition: !input transition_time
      - conditions: "{{ command == 'off_press' }}"
        sequence:
          - service: scene_presets.apply_preset
            data:
              preset_id: "{{ included_scenes[current_scene] }}"
              targets:
                entity_id: !input light
              shuffle: false
              smart_shuffle: false
          - service: input_text.set_value
            target:
              entity_id: !input scene_helper
            data:
              value: >
                {{ {"scene": (current_scene + 1) % included_scenes | length, "timestamp": as_timestamp(now())} | to_json }}
